/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oomtest;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author sath
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    boolean isMakeSalePanelActive;
    boolean isInventoryPanelActive;
    boolean isCustomersTableActive;
    boolean isSalesHistoryTableActive;
    boolean isViewInstallmentsTableActive;
    boolean isUsersSettingsPanelActive;
    public Home() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        

    }

    public void resetButtonsColors(){
        makeSaleButton.setBackground(new Color(244, 244, 244));
        inventoryButton.setBackground(new Color(244, 244, 244));
        customersButton.setBackground(new Color(244, 244, 244));
        salesHistoryButton.setBackground(new Color(244, 244, 244));
        viewInstallmentsButton.setBackground(new Color(244, 244, 244));
        usersSettingsButton.setBackground(new Color(244, 244, 244));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        makeSaleButton = new javax.swing.JButton();
        inventoryButton = new javax.swing.JButton();
        customersButton = new javax.swing.JButton();
        salesHistoryButton = new javax.swing.JButton();
        viewInstallmentsButton = new javax.swing.JButton();
        usersSettingsButton = new javax.swing.JButton();
        parentPanel = new javax.swing.JPanel();
        makeSalePanel = new javax.swing.JScrollPane();
        makeSalePane = new javax.swing.JPanel();
        customerDetailsLabel = new javax.swing.JLabel();
        customerDetailsSeperator = new javax.swing.JSeparator();
        idNumLabel = new javax.swing.JLabel();
        idNumField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        contactNumLabel = new javax.swing.JLabel();
        contactNumeField = new javax.swing.JTextField();
        bankAccountNumLabel = new javax.swing.JLabel();
        bankAccountNumField = new javax.swing.JTextField();
        permanentAddressLabel = new javax.swing.JLabel();
        permanentAddressField = new javax.swing.JTextField();
        currentAddressLabel = new javax.swing.JLabel();
        currentAddressField = new javax.swing.JTextField();
        contentSepratorOne = new javax.swing.JSeparator();
        motorcycleDetailsLabel = new javax.swing.JLabel();
        motorcycleDetailsSeparator = new javax.swing.JSeparator();
        brandLabel = new javax.swing.JLabel();
        brandDropDownMenu = new javax.swing.JComboBox<>();
        modelLabel = new javax.swing.JLabel();
        modelDropDownMenu = new javax.swing.JComboBox<>();
        boardNumLabel = new javax.swing.JLabel();
        boardNumField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        currentPriceLabel = new javax.swing.JLabel();
        installmentLabel = new javax.swing.JLabel();
        installmentCheckBox = new javax.swing.JCheckBox();
        installmentPeriodLabel = new javax.swing.JLabel();
        installmendPeriodlDropDownMenu = new javax.swing.JComboBox<>();
        confirmSaleButton = new javax.swing.JButton();
        inventoryPanel = new javax.swing.JPanel();
        inventoryTable = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        inventoryMenu = new javax.swing.JPanel();
        addToInventoryButton = new javax.swing.JButton();
        modifyInventoryButton = new javax.swing.JButton();
        removeInventoryButton = new javax.swing.JButton();
        customersTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        salesHistoryTable = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        viewInstallmentsTable = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        usersSettingsPanel = new javax.swing.JPanel();
        usersTable = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        usersMenu = new javax.swing.JPanel();
        addUsers = new javax.swing.JButton();
        modifyUser = new javax.swing.JButton();
        removeInventoryButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setBackground(new java.awt.Color(19, 15, 64));

        makeSaleButton.setBackground(new java.awt.Color(161, 202, 141));
        makeSaleButton.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        makeSaleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/make_sale.png"))); // NOI18N
        makeSaleButton.setText("  Sale                            ");
        makeSaleButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        makeSaleButton.setContentAreaFilled(false);
        makeSaleButton.setOpaque(true);
        makeSaleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                makeSaleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                makeSaleButtonMouseExited(evt);
            }
        });
        makeSaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeSaleButtonActionPerformed(evt);
            }
        });

        inventoryButton.setBackground(new java.awt.Color(244, 244, 244));
        inventoryButton.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        inventoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inventory.png"))); // NOI18N
        inventoryButton.setText("  Inventory                     ");
        inventoryButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inventoryButton.setContentAreaFilled(false);
        inventoryButton.setOpaque(true);
        inventoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryButtonMouseExited(evt);
            }
        });
        inventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryButtonActionPerformed(evt);
            }
        });

        customersButton.setBackground(new java.awt.Color(244, 244, 244));
        customersButton.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        customersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customers.png"))); // NOI18N
        customersButton.setText("  Customers                   ");
        customersButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        customersButton.setContentAreaFilled(false);
        customersButton.setOpaque(true);
        customersButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customersButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customersButtonMouseExited(evt);
            }
        });
        customersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersButtonActionPerformed(evt);
            }
        });

        salesHistoryButton.setBackground(new java.awt.Color(244, 244, 244));
        salesHistoryButton.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        salesHistoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sales_history.png"))); // NOI18N
        salesHistoryButton.setText("  Sales History                ");
        salesHistoryButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        salesHistoryButton.setContentAreaFilled(false);
        salesHistoryButton.setOpaque(true);
        salesHistoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salesHistoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salesHistoryButtonMouseExited(evt);
            }
        });
        salesHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesHistoryButtonActionPerformed(evt);
            }
        });

        viewInstallmentsButton.setBackground(new java.awt.Color(244, 244, 244));
        viewInstallmentsButton.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        viewInstallmentsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/installments.png"))); // NOI18N
        viewInstallmentsButton.setText(" Installments                 ");
        viewInstallmentsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        viewInstallmentsButton.setContentAreaFilled(false);
        viewInstallmentsButton.setOpaque(true);
        viewInstallmentsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewInstallmentsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewInstallmentsButtonMouseExited(evt);
            }
        });
        viewInstallmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInstallmentsButtonActionPerformed(evt);
            }
        });

        usersSettingsButton.setBackground(new java.awt.Color(244, 244, 244));
        usersSettingsButton.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        usersSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_settings.png"))); // NOI18N
        usersSettingsButton.setText("  Users                           ");
        usersSettingsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        usersSettingsButton.setContentAreaFilled(false);
        usersSettingsButton.setOpaque(true);
        usersSettingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersSettingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersSettingsButtonMouseExited(evt);
            }
        });
        usersSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersSettingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(makeSaleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(salesHistoryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(customersButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewInstallmentsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(usersSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(makeSaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salesHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewInstallmentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usersSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        parentPanel.setBackground(new java.awt.Color(223, 249, 251));
        parentPanel.setLayout(new java.awt.CardLayout());

        makeSalePanel.setBackground(new java.awt.Color(255, 255, 255));
        makeSalePanel.setBorder(null);
        makeSalePanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        makeSalePane.setBackground(new java.awt.Color(255, 255, 255));

        customerDetailsLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        customerDetailsLabel.setText("Customer Details");

        customerDetailsSeperator.setBackground(new java.awt.Color(204, 204, 204));

        idNumLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        idNumLabel.setText("NID/Passport No:");

        idNumField.setBackground(new java.awt.Color(229, 229, 229));
        idNumField.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        idNumField.setBorder(null);

        firstNameLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        firstNameLabel.setText("First Name:");

        firstNameField.setBackground(new java.awt.Color(229, 229, 229));
        firstNameField.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        firstNameField.setBorder(null);

        lastNameLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lastNameLabel.setText("Last Name:");

        lastNameField.setBackground(new java.awt.Color(229, 229, 229));
        lastNameField.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        lastNameField.setBorder(null);

        contactNumLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        contactNumLabel.setText("Contact No:");

        contactNumeField.setBackground(new java.awt.Color(229, 229, 229));
        contactNumeField.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        contactNumeField.setBorder(null);

        bankAccountNumLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        bankAccountNumLabel.setText("Bank Account No:");

        bankAccountNumField.setBackground(new java.awt.Color(229, 229, 229));
        bankAccountNumField.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        bankAccountNumField.setBorder(null);

        permanentAddressLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        permanentAddressLabel.setText("Parmenent Address:");

        permanentAddressField.setBackground(new java.awt.Color(229, 229, 229));
        permanentAddressField.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        permanentAddressField.setBorder(null);

        currentAddressLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        currentAddressLabel.setText("Current Address:");

        currentAddressField.setBackground(new java.awt.Color(229, 229, 229));
        currentAddressField.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        currentAddressField.setBorder(null);

        contentSepratorOne.setBackground(new java.awt.Color(204, 204, 204));

        motorcycleDetailsLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        motorcycleDetailsLabel.setText("Motorcycle Details");

        motorcycleDetailsSeparator.setBackground(new java.awt.Color(204, 204, 204));

        brandLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        brandLabel.setText("Brand:");

        brandDropDownMenu.setBackground(new java.awt.Color(229, 229, 229));
        brandDropDownMenu.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        brandDropDownMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        brandDropDownMenu.setBorder(null);

        modelLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        modelLabel.setText("Model:");

        modelDropDownMenu.setBackground(new java.awt.Color(229, 229, 229));
        modelDropDownMenu.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        modelDropDownMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        modelDropDownMenu.setBorder(null);

        boardNumLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        boardNumLabel.setText("Board No:");

        boardNumField.setBackground(new java.awt.Color(229, 229, 229));
        boardNumField.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        boardNumField.setBorder(null);

        priceLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        priceLabel.setText("Price:");

        currentPriceLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        currentPriceLabel.setText("Motorcycle Price");

        installmentLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        installmentLabel.setText("Installment:");

        installmentCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        installmentCheckBox.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N

        installmentPeriodLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        installmentPeriodLabel.setText("Installment Period:");

        installmendPeriodlDropDownMenu.setBackground(new java.awt.Color(229, 229, 229));
        installmendPeriodlDropDownMenu.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        installmendPeriodlDropDownMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  6 Months", "12 Months", "18 Months", "24 Months" }));
        installmendPeriodlDropDownMenu.setBorder(null);

        confirmSaleButton.setBackground(new java.awt.Color(209, 229, 199));
        confirmSaleButton.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 14)); // NOI18N
        confirmSaleButton.setText("Confirm");
        confirmSaleButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        confirmSaleButton.setContentAreaFilled(false);
        confirmSaleButton.setOpaque(true);
        confirmSaleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmSaleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmSaleButtonMouseExited(evt);
            }
        });
        confirmSaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmSaleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout makeSalePaneLayout = new javax.swing.GroupLayout(makeSalePane);
        makeSalePane.setLayout(makeSalePaneLayout);
        makeSalePaneLayout.setHorizontalGroup(
            makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentSepratorOne)
            .addGroup(makeSalePaneLayout.createSequentialGroup()
                .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(makeSalePaneLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(contactNumLabel)
                        .addGap(86, 86, 86)
                        .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactNumeField, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(makeSalePaneLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerDetailsLabel)
                            .addComponent(customerDetailsSeperator)
                            .addComponent(idNumLabel))
                        .addGap(17, 17, 17))
                    .addGroup(makeSalePaneLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(motorcycleDetailsLabel)
                            .addComponent(motorcycleDetailsSeparator)
                            .addGroup(makeSalePaneLayout.createSequentialGroup()
                                .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(makeSalePaneLayout.createSequentialGroup()
                                        .addComponent(brandLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(brandDropDownMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, makeSalePaneLayout.createSequentialGroup()
                                        .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(makeSalePaneLayout.createSequentialGroup()
                                                .addComponent(priceLabel)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, makeSalePaneLayout.createSequentialGroup()
                                                .addGap(0, 4, Short.MAX_VALUE)
                                                .addComponent(boardNumLabel)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(currentPriceLabel)
                                            .addComponent(boardNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(43, 43, 43)
                                .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(makeSalePaneLayout.createSequentialGroup()
                                        .addComponent(modelLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modelDropDownMenu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(makeSalePaneLayout.createSequentialGroup()
                                        .addComponent(installmentPeriodLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(installmendPeriodlDropDownMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(makeSalePaneLayout.createSequentialGroup()
                                        .addComponent(installmentLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(installmentCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18))
                    .addGroup(makeSalePaneLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel)
                            .addComponent(lastNameLabel)))
                    .addGroup(makeSalePaneLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bankAccountNumLabel)
                            .addComponent(permanentAddressLabel)
                            .addComponent(currentAddressLabel))
                        .addGap(18, 18, 18)
                        .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(makeSalePaneLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(bankAccountNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(permanentAddressField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentAddressField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(76, 76, 76))
            .addComponent(confirmSaleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        makeSalePaneLayout.setVerticalGroup(
            makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makeSalePaneLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(customerDetailsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerDetailsSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idNumLabel)
                    .addComponent(idNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel))
                .addGap(38, 38, 38)
                .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel))
                .addGap(44, 44, 44)
                .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumeField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNumLabel))
                .addGap(52, 52, 52)
                .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankAccountNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankAccountNumLabel))
                .addGap(48, 48, 48)
                .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permanentAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(permanentAddressLabel))
                .addGap(45, 45, 45)
                .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentAddressLabel))
                .addGap(52, 52, 52)
                .addComponent(contentSepratorOne, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(motorcycleDetailsLabel)
                .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(makeSalePaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(motorcycleDetailsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brandLabel)
                            .addComponent(brandDropDownMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelLabel)
                            .addComponent(modelDropDownMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boardNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boardNumLabel)
                            .addComponent(installmentLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, makeSalePaneLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(installmentCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(makeSalePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentPriceLabel)
                    .addComponent(priceLabel)
                    .addComponent(installmentPeriodLabel)
                    .addComponent(installmendPeriodlDropDownMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(confirmSaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        makeSalePanel.setViewportView(makeSalePane);

        parentPanel.add(makeSalePanel, "card2");

        jTable4.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        inventoryTable.setViewportView(jTable4);

        inventoryMenu.setBackground(new java.awt.Color(19, 15, 64));

        addToInventoryButton.setBackground(new java.awt.Color(244, 244, 244));
        addToInventoryButton.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        addToInventoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        addToInventoryButton.setText("  Add                                    ");
        addToInventoryButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addToInventoryButton.setContentAreaFilled(false);
        addToInventoryButton.setOpaque(true);
        addToInventoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addToInventoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addToInventoryButtonMouseExited(evt);
            }
        });
        addToInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToInventoryButtonActionPerformed(evt);
            }
        });

        modifyInventoryButton.setBackground(new java.awt.Color(244, 244, 244));
        modifyInventoryButton.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        modifyInventoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/modify.png"))); // NOI18N
        modifyInventoryButton.setText("  Modify                              ");
        modifyInventoryButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        modifyInventoryButton.setContentAreaFilled(false);
        modifyInventoryButton.setOpaque(true);
        modifyInventoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modifyInventoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modifyInventoryButtonMouseExited(evt);
            }
        });
        modifyInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyInventoryButtonActionPerformed(evt);
            }
        });

        removeInventoryButton.setBackground(new java.awt.Color(244, 244, 244));
        removeInventoryButton.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        removeInventoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/remove.png"))); // NOI18N
        removeInventoryButton.setText("  Remove                            ");
        removeInventoryButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        removeInventoryButton.setContentAreaFilled(false);
        removeInventoryButton.setOpaque(true);
        removeInventoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeInventoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeInventoryButtonMouseExited(evt);
            }
        });
        removeInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeInventoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inventoryMenuLayout = new javax.swing.GroupLayout(inventoryMenu);
        inventoryMenu.setLayout(inventoryMenuLayout);
        inventoryMenuLayout.setHorizontalGroup(
            inventoryMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addToInventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(modifyInventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(removeInventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        inventoryMenuLayout.setVerticalGroup(
            inventoryMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryMenuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(addToInventoryButton)
                .addGap(32, 32, 32)
                .addComponent(removeInventoryButton)
                .addGap(33, 33, 33)
                .addComponent(modifyInventoryButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout inventoryPanelLayout = new javax.swing.GroupLayout(inventoryPanel);
        inventoryPanel.setLayout(inventoryPanelLayout);
        inventoryPanelLayout.setHorizontalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inventoryTable, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inventoryMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        inventoryPanelLayout.setVerticalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inventoryTable, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(inventoryMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        parentPanel.add(inventoryPanel, "card3");

        jTable1.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        customersTable.setViewportView(jTable1);

        parentPanel.add(customersTable, "card4");

        jTable2.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        salesHistoryTable.setViewportView(jTable2);

        parentPanel.add(salesHistoryTable, "card5");

        jTable3.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        viewInstallmentsTable.setViewportView(jTable3);

        parentPanel.add(viewInstallmentsTable, "card6");

        jTable5.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        usersTable.setViewportView(jTable5);

        usersMenu.setBackground(new java.awt.Color(19, 15, 64));

        addUsers.setBackground(new java.awt.Color(244, 244, 244));
        addUsers.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        addUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        addUsers.setText("  Add                                    ");
        addUsers.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addUsers.setContentAreaFilled(false);
        addUsers.setOpaque(true);
        addUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addUsersMouseExited(evt);
            }
        });
        addUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUsersActionPerformed(evt);
            }
        });

        modifyUser.setBackground(new java.awt.Color(244, 244, 244));
        modifyUser.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        modifyUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/modify.png"))); // NOI18N
        modifyUser.setText("  Modify                              ");
        modifyUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        modifyUser.setContentAreaFilled(false);
        modifyUser.setOpaque(true);
        modifyUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modifyUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modifyUserMouseExited(evt);
            }
        });
        modifyUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyUserActionPerformed(evt);
            }
        });

        removeInventoryButton1.setBackground(new java.awt.Color(244, 244, 244));
        removeInventoryButton1.setFont(new java.awt.Font("NewsGoth Lt BT", 0, 14)); // NOI18N
        removeInventoryButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/remove.png"))); // NOI18N
        removeInventoryButton1.setText("  Remove                            ");
        removeInventoryButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        removeInventoryButton1.setContentAreaFilled(false);
        removeInventoryButton1.setOpaque(true);
        removeInventoryButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeInventoryButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeInventoryButton1MouseExited(evt);
            }
        });
        removeInventoryButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeInventoryButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usersMenuLayout = new javax.swing.GroupLayout(usersMenu);
        usersMenu.setLayout(usersMenuLayout);
        usersMenuLayout.setHorizontalGroup(
            usersMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(modifyUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(removeInventoryButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        usersMenuLayout.setVerticalGroup(
            usersMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersMenuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(addUsers)
                .addGap(32, 32, 32)
                .addComponent(removeInventoryButton1)
                .addGap(33, 33, 33)
                .addComponent(modifyUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout usersSettingsPanelLayout = new javax.swing.GroupLayout(usersSettingsPanel);
        usersSettingsPanel.setLayout(usersSettingsPanelLayout);
        usersSettingsPanelLayout.setHorizontalGroup(
            usersSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usersTable, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usersMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        usersSettingsPanelLayout.setVerticalGroup(
            usersSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usersTable, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(usersMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        parentPanel.add(usersSettingsPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void makeSaleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeSaleButtonMouseEntered
        // TODO add your handling code here:
        if(isMakeSalePanelActive == true){
            makeSaleButton.setBackground(new Color(178, 229, 153));
        }else{
            makeSaleButton.setBackground(new Color(229, 229, 229));
        }
        
            
    }//GEN-LAST:event_makeSaleButtonMouseEntered

    private void makeSaleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeSaleButtonMouseExited
        // TODO add your handling code here:
        if(isMakeSalePanelActive == true){
            makeSaleButton.setBackground(new Color(161,202,141));
        }else{
            makeSaleButton.setBackground(new Color(244,244,244));
        }
        
        
        
    }//GEN-LAST:event_makeSaleButtonMouseExited

    private void salesHistoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesHistoryButtonMouseEntered
        // TODO add your handling code here:
        if(isSalesHistoryTableActive == true){
            salesHistoryButton.setBackground(new Color(178, 229, 153));
        }else{
            salesHistoryButton.setBackground(new Color(229, 229, 229));
        }
    }//GEN-LAST:event_salesHistoryButtonMouseEntered

    private void salesHistoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesHistoryButtonMouseExited
        // TODO add your handling code here:
        if(isSalesHistoryTableActive == true){
            salesHistoryButton.setBackground(new Color(161,202,141));
        }else{
            salesHistoryButton.setBackground(new Color(244, 244, 244));
        }
    }//GEN-LAST:event_salesHistoryButtonMouseExited

    private void inventoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryButtonMouseEntered
        // TODO add your handling code here:
        if(isInventoryPanelActive == true){
            inventoryButton.setBackground(new Color(178, 229, 153));
        }else{
            inventoryButton.setBackground(new Color(229, 229, 229));
        }
    }//GEN-LAST:event_inventoryButtonMouseEntered

    private void inventoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryButtonMouseExited
        // TODO add your handling code here:
        if(isInventoryPanelActive == true){
            inventoryButton.setBackground(new Color(161,202,141));
        }else{
            inventoryButton.setBackground(new Color(244, 244, 244));
        }
    }//GEN-LAST:event_inventoryButtonMouseExited

    private void customersButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersButtonMouseEntered
        // TODO add your handling code here:
        if(isCustomersTableActive == true){
            customersButton.setBackground(new Color(178, 229, 153));
        }else{
            customersButton.setBackground(new Color(229, 229, 229));
        }
    }//GEN-LAST:event_customersButtonMouseEntered

    private void customersButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersButtonMouseExited
        // TODO add your handling code here:
        if(isCustomersTableActive == true){
            customersButton.setBackground(new Color(161,202,141));
        }else{
            customersButton.setBackground(new Color(244, 244, 244));
        }
    }//GEN-LAST:event_customersButtonMouseExited

    private void usersSettingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersSettingsButtonMouseEntered
        // TODO add your handling code here:
       if(isViewInstallmentsTableActive == true){
            usersSettingsButton.setBackground(new Color(178, 229, 153));
        }else{
            usersSettingsButton.setBackground(new Color(229, 229, 229));
        }
    }//GEN-LAST:event_usersSettingsButtonMouseEntered

    private void usersSettingsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersSettingsButtonMouseExited
        // TODO add your handling code here:
        if(isViewInstallmentsTableActive == true){
            usersSettingsButton.setBackground(new Color(161,202,141));
        }else{
            usersSettingsButton.setBackground(new Color(244, 244, 244));
        }
    }//GEN-LAST:event_usersSettingsButtonMouseExited

    private void salesHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesHistoryButtonActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(salesHistoryTable);
        parentPanel.repaint();
        parentPanel.revalidate();
        
        resetButtonsColors();
        salesHistoryButton.setBackground(new Color(197, 223, 185));
        
        isMakeSalePanelActive = false;
        isInventoryPanelActive = false;
        isCustomersTableActive = false;
        isSalesHistoryTableActive = true;
        isViewInstallmentsTableActive = false;
        isUsersSettingsPanelActive = false;
    }//GEN-LAST:event_salesHistoryButtonActionPerformed

    private void viewInstallmentsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewInstallmentsButtonMouseEntered
        // TODO add your handling code here:
        if(isUsersSettingsPanelActive == true){
            viewInstallmentsButton.setBackground(new Color(178, 229, 153));
        }else{
            viewInstallmentsButton.setBackground(new Color(229, 229, 229));
        }
    }//GEN-LAST:event_viewInstallmentsButtonMouseEntered

    private void viewInstallmentsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewInstallmentsButtonMouseExited
        // TODO add your handling code here:
        if(isUsersSettingsPanelActive == true){
            viewInstallmentsButton.setBackground(new Color(161,202,141));
        }else{
            viewInstallmentsButton.setBackground(new Color(244, 244, 244));
        }
    }//GEN-LAST:event_viewInstallmentsButtonMouseExited

    private void makeSaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeSaleButtonActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(makeSalePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
        resetButtonsColors();
        makeSaleButton.setBackground(new Color(197, 223, 185));
        
        isMakeSalePanelActive = true;
        isInventoryPanelActive = false;
        isCustomersTableActive = false;
        isSalesHistoryTableActive = false;
        isViewInstallmentsTableActive = false;
        isUsersSettingsPanelActive = false;
    }//GEN-LAST:event_makeSaleButtonActionPerformed

    private void confirmSaleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmSaleButtonMouseEntered
        // TODO add your handling code here:
         confirmSaleButton.setBackground(new Color(182, 215, 168));
        
    }//GEN-LAST:event_confirmSaleButtonMouseEntered

    private void confirmSaleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmSaleButtonMouseExited
        // TODO add your handling code here:
        confirmSaleButton.setBackground(new Color(209, 229, 199));
    }//GEN-LAST:event_confirmSaleButtonMouseExited

    private void confirmSaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmSaleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmSaleButtonActionPerformed

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(inventoryPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
        
        resetButtonsColors();
        inventoryButton.setBackground(new Color(197, 223, 185));
        
        isMakeSalePanelActive = false;
        isInventoryPanelActive = true;
        isCustomersTableActive = false;
        isSalesHistoryTableActive = false;
        isViewInstallmentsTableActive = false;
        isUsersSettingsPanelActive = false;
    }//GEN-LAST:event_inventoryButtonActionPerformed

    private void customersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersButtonActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(customersTable);
        parentPanel.repaint();
        parentPanel.revalidate();
        
        resetButtonsColors();
        customersButton.setBackground(new Color(197, 223, 185));
        
        isMakeSalePanelActive = false;
        isInventoryPanelActive = false;
        isCustomersTableActive = true;
        isSalesHistoryTableActive = false;
        isViewInstallmentsTableActive = false;
        isUsersSettingsPanelActive = false;
    }//GEN-LAST:event_customersButtonActionPerformed

    private void usersSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersSettingsButtonActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(usersSettingsPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
        
        resetButtonsColors();
        usersSettingsButton.setBackground(new Color(197, 223, 185));
        
        isMakeSalePanelActive = false;
        isInventoryPanelActive = false;
        isCustomersTableActive = false;
        isSalesHistoryTableActive = false;
        isViewInstallmentsTableActive = true;
        isUsersSettingsPanelActive = false;
    }//GEN-LAST:event_usersSettingsButtonActionPerformed

    private void viewInstallmentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInstallmentsButtonActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(viewInstallmentsTable);
        parentPanel.repaint();
        parentPanel.revalidate();
        
        resetButtonsColors();
        viewInstallmentsButton.setBackground(new Color(197, 223, 185));
        
        isMakeSalePanelActive = false;
        isInventoryPanelActive = false;
        isCustomersTableActive = false;
        isSalesHistoryTableActive = false;
        isViewInstallmentsTableActive = false;
        isUsersSettingsPanelActive = true;
    }//GEN-LAST:event_viewInstallmentsButtonActionPerformed

    private void addToInventoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToInventoryButtonMouseEntered
        // TODO add your handling code here:
        addToInventoryButton.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_addToInventoryButtonMouseEntered

    private void addToInventoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToInventoryButtonMouseExited
        // TODO add your handling code here:
        addToInventoryButton.setBackground(new Color(209, 229, 199));
    }//GEN-LAST:event_addToInventoryButtonMouseExited

    private void addToInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToInventoryButtonActionPerformed
        // TODO add your handling code here:
        AddToInventory addToInventory = new AddToInventory();
        addToInventory.setVisible(true);
    }//GEN-LAST:event_addToInventoryButtonActionPerformed

    private void modifyInventoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyInventoryButtonMouseEntered
        // TODO add your handling code here:
        modifyInventoryButton.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_modifyInventoryButtonMouseEntered

    private void modifyInventoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyInventoryButtonMouseExited
        // TODO add your handling code here:
        modifyInventoryButton.setBackground(new Color(209, 229, 199));
    }//GEN-LAST:event_modifyInventoryButtonMouseExited

    private void modifyInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyInventoryButtonActionPerformed
        // TODO add your handling code here:
        ModifyInventory modifyInventory = new ModifyInventory();
        modifyInventory.setVisible(true);
    }//GEN-LAST:event_modifyInventoryButtonActionPerformed

    private void removeInventoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeInventoryButtonMouseEntered
        // TODO add your handling code here:
        removeInventoryButton.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_removeInventoryButtonMouseEntered

    private void removeInventoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeInventoryButtonMouseExited
        // TODO add your handling code here:
        removeInventoryButton.setBackground(new Color(209, 229, 199));
    }//GEN-LAST:event_removeInventoryButtonMouseExited

    private void removeInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeInventoryButtonActionPerformed
        // TODO add your handling code here:
        RemoveInventory removeInventory = new RemoveInventory();
        removeInventory.setVisible(true);
    }//GEN-LAST:event_removeInventoryButtonActionPerformed

    private void addUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUsersMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addUsersMouseEntered

    private void addUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUsersMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addUsersMouseExited

    private void addUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUsersActionPerformed
        // TODO add your handling code here:
        AddUser addUser = new AddUser();
        addUser.setVisible(true);
        
    }//GEN-LAST:event_addUsersActionPerformed

    private void modifyUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyUserMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyUserMouseEntered

    private void modifyUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyUserMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyUserMouseExited

    private void modifyUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyUserActionPerformed

    private void removeInventoryButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeInventoryButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_removeInventoryButton1MouseEntered

    private void removeInventoryButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeInventoryButton1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_removeInventoryButton1MouseExited

    private void removeInventoryButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeInventoryButton1ActionPerformed
        // TODO add your handling code here:
        RemoveUser removeUser = new RemoveUser();
        removeUser.setVisible(true);
    }//GEN-LAST:event_removeInventoryButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToInventoryButton;
    private javax.swing.JButton addUsers;
    private javax.swing.JTextField bankAccountNumField;
    private javax.swing.JLabel bankAccountNumLabel;
    private javax.swing.JTextField boardNumField;
    private javax.swing.JLabel boardNumLabel;
    private javax.swing.JComboBox<String> brandDropDownMenu;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JButton confirmSaleButton;
    private javax.swing.JLabel contactNumLabel;
    private javax.swing.JTextField contactNumeField;
    private javax.swing.JSeparator contentSepratorOne;
    private javax.swing.JTextField currentAddressField;
    private javax.swing.JLabel currentAddressLabel;
    private javax.swing.JLabel currentPriceLabel;
    private javax.swing.JLabel customerDetailsLabel;
    private javax.swing.JSeparator customerDetailsSeperator;
    private javax.swing.JButton customersButton;
    private javax.swing.JScrollPane customersTable;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField idNumField;
    private javax.swing.JLabel idNumLabel;
    private javax.swing.JComboBox<String> installmendPeriodlDropDownMenu;
    private javax.swing.JCheckBox installmentCheckBox;
    private javax.swing.JLabel installmentLabel;
    private javax.swing.JLabel installmentPeriodLabel;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JPanel inventoryMenu;
    private javax.swing.JPanel inventoryPanel;
    private javax.swing.JScrollPane inventoryTable;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton makeSaleButton;
    private javax.swing.JPanel makeSalePane;
    private javax.swing.JScrollPane makeSalePanel;
    private javax.swing.JPanel menu;
    private javax.swing.JComboBox<String> modelDropDownMenu;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JButton modifyInventoryButton;
    private javax.swing.JButton modifyUser;
    private javax.swing.JLabel motorcycleDetailsLabel;
    private javax.swing.JSeparator motorcycleDetailsSeparator;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JTextField permanentAddressField;
    private javax.swing.JLabel permanentAddressLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton removeInventoryButton;
    private javax.swing.JButton removeInventoryButton1;
    private javax.swing.JButton salesHistoryButton;
    private javax.swing.JScrollPane salesHistoryTable;
    private javax.swing.JPanel usersMenu;
    private javax.swing.JButton usersSettingsButton;
    private javax.swing.JPanel usersSettingsPanel;
    private javax.swing.JScrollPane usersTable;
    private javax.swing.JButton viewInstallmentsButton;
    private javax.swing.JScrollPane viewInstallmentsTable;
    // End of variables declaration//GEN-END:variables
}

